### ISSUE TITLE
Secret key not readable after key armor transferred between device

### ISSUE THREAD

**Issue by MainasuK** [DimensionDev/Tessercube-iOS#89]
Tessercube 1.3.2 (37)

1. Create the RSA key in Tessercube (Not sure Android or iOS)
2. Import in Tessercube iOS.
3. The "Contract" tab display that key with the correct name
3. But not appear in the "Me" tab

Expect: secret key should display in the "Me" tab

P.S.
`$0.hasSecretKey` may return wrong value.
```swift
ProfileService.default.keys.asDriver()
            .map { $0.filter { $0.hasSecretKey } }
            .drive(keys)
            .disposed(by: disposeBag)
```

**Comment by MainasuK** [comment]
Update：
The user import that key as `Contract` before. If remove that contract then import as the secret key. Issue not appear. 

The second time import as secret key maybe not update the passphrase into the keychain.

**Comment by MainasuK** [comment]
WIP

**Comment by MainasuK** [comment]
Test under 1.3.2:

## Test case 1:
1. Exports the private key which has an empty passphrase in device A
2. Import this private key as Contract in device B
3. Key imported in Contract and Me list
4. Send encrypt a message with this key in device A
5. Decrypt message in device B
6. No error

## Test case 2:
1. Exports the private key which has a non-empty passphrase in device A
2. Import this private key as Contract in device B
3. App crash

```
panic: interface conversion: interface is nil, not crypto.Signer

goroutine 17 [running, locked to thread]:
golang.org/x/crypto/openpgp/packet.(*Signature).Sign(0xc000356900, 0x10828d520, 0xc000198500, 0xc000356300, 0x0, 0xc000198500, 0x0)
	/Users/jk234ert/go/src/golang.org/x/crypto/openpgp/packet/signature.go:543 +0x12f
golang.org/x/crypto/openpgp/packet.(*Signature).SignUserId(0xc000356900, 0xc000268a20, 0x1f, 0xc0002c7ce0, 0xc000356300, 0x0, 0x28, 0xc0001805d0)
	/Users/jk234ert/go/src/golang.org/x/crypto/openpgp/packet/signature.go:611 +0xb0
golang.org/x/crypto/openpgp.(*Entity).SelfSign(0xc000192550, 0x0, 0x1, 0x1)
	/Users/jk234ert/go/src/golang.org/x/crypto/openpgp/keys.go:589 +0xe1
github.com/DimensionDev/gopenpgp/crypto.(*KeyRing).GetArmored(0xc000233c80, 0x0, 0x0, 0x0, 0x10818c890, 0xc0001a3d78, 0xc0001a3d90)
	/Users/jk234ert/go/src/github.com/DimensionDev/gopenpgp/crypto/keyring.go:205 +0x215
main.proxycrypto_KeyRing_GetArmored(0xc0fffffe7a, 0x0, 0x100000000, 0x0, 0x0, 0xc0000ca090)
	/var/folders/8w/sbdghlnx1wjb2x5nd649pcgw0000gn/T/gomobile-work-786662663/src/gobind/go_cryptomain.go:710 +0x95
main._cgoexpwrap_78fade515b5d_proxycrypto_KeyRing_GetArmored(0x7fb5fffffe7a, 0x0, 0x100000000, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:972 +0x86
```

## Test case 3:
1. Exports the private key which has a non-empty passphrase in device A
2. Import *public part* of this private key as Contract in device B
3. Key imported success as the contract but not display in Me list
4. Import this private key 
5. Key imported success but not display in Me list
(Expect this key imported as private key but not)

**Comment by MainasuK** [comment]
## Test case 4:
1. Exports the private key which has a non-empty passphrase in device A
2. Import the public key part of this key as a private key (use key import entry in Me tab)  in device B
3. App crash without stack info

## Test case 5:
1. Exports the private key which has a non-empty passphrase in device A
2. Import the private key part without the public key part of this key as a private key (use key import entry in Me tab)  in device B
3. Key imported success
